;show_widget=true

[System Settings]

[*Fan Curve]
;mode=forwarder
package_source './fan_curve.ini'

[GPU Scheduling]
;mode=toggle?on
;mini=true
on:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x1
refresh
off:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x0
refresh

[sys-clk-hoc  hoc-clk]
;mode=toggle?off
;mini=true
on:
cp ./modules/hoc-clk/00FF0000636C6BFF/ /atmosphere/contents/00FF0000636C6BFF/
try:
path_exists /switch/.overlays/ovlSysmodules.ovl
open /switch/.overlays/ovlSysmodules.ovl
off:
cp ./modules/sys-clk-hoc/00FF0000636C6BFF/ /atmosphere/contents/00FF0000636C6BFF/
try:
path_exists /switch/.overlays/ovlSysmodules.ovl
open /switch/.overlays/ovlSysmodules.ovl

[Always Save Cheats]
;mode=toggle?on
;mini=true
on:
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_always_save_cheat_toggles u8!0x1
refresh
off:
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_always_save_cheat_toggles u8!0x0
refresh

[Controller Sync]
;mode=toggle
;mini=true
on:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x1
off:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x0

[Hold R for HB Menu]
;mode=toggle
;mini=true
on:
set-ini-val /atmosphere/config/override_config.ini hbl_config override_key R
off:
set-ini-val /atmosphere/config/override_config.ini hbl_config override_key !R


mariko:
[Notice]
[GPU Scheduling Notice Table2]
;system=mariko
;mode=table
;background=true
;wrapping_mode=word
;spacing=4
;gap=25
;section_text_color=warning
'The combination of Scheduling OFF and 1305 MHz exceeds the pmic limit.' = ''