;title='HOC Toolkit'
;version=2.0.0
;creator='ppkantorski, B3711, NaGa, MestreYodaRossi'
;about='This package was designed for advance oc configurations on HOC 2.1.0. Use with caution and proper guidance.'
;show_widget=true

[Module Info]

[Module Info Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
hex_file /atmosphere/kips/hoc.kip

'Title'='Horizon OC'
'Version'='{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},0,1)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},1,2)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},2,3)}'
'└ kip'='rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'
'Credits'='Lightos, Souldbminer, Hanai3bi,'
''='NaGaa95, B3711, KazushiMe,'
''='RetroNX Team, MasaGratoR,'
''='ppkantorski, Dominatorul,'
''='ZachyCatGames, TDRR,'
''='tetetete-ctrl, SciresM, CTCaer'

[Package Info]
