;title='HOC Toolkit'
;version='2.0.0  KIP Rev 2'
;creator='ppkantorski, B3711, NaGa, MestreYodaRossi'
;about='This package was designed for advance overclocking configurations with HOC. Use with caution and proper guidance.'
;color=green
;show_widget=true


[Module Info]

[Module Info Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;wrapping_mode=word

hex_file /atmosphere/kips/hoc.kip

'Title'='Horizon OC'
'Version'='{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},0,1)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},1,2)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},2,3)}  KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'
'Creator(s)'='Lightos, Souldbminer, Hanai3bi, NaGaa95, B3711, KazushiMe, RetroNX Team, MasaGratoR, ppkantorski, Dominatorul, ZachyCatGames, TDRR, tetetete-ctrl, SciresM, CTCaer'

[Package Info]