;show_widget=true

[Advanced Latency]

[*Read Latency 0?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 100 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Read Latency 1?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 104 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Read Latency 2?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 108 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Read Latency 3?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 112 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[gap]
;mode=table
;background=false
;gap=20


[*Write Latency 0?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 116 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Write Latency 1?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 120 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Write Latency 2?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 124 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Write Latency 3?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/latency_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 128 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
