;show_widget=true

[Custom Table]
[*76 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 328 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*153 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 332 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*230 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 336 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*307 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 340 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*384 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 344 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*460 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 348 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*537 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 352 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*614 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 356 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*691 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 360 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*768 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 364 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*844 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 368 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*921 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 372 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*998 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 376 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1075 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_high_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 380 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1152 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_high_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 384 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1228 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_high_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 388 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1267 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 392 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1305 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 396 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1344 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 400 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1382 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 404 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1420 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 408 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1459 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 412 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1497 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 416 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1536 MHz?GPUUV3mariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_mariko_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 420 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*76 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 220 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*115 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 224 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*153 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 228 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*192 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 232 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*230 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 236 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*269 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 240 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*307 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 244 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*346 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 248 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*384 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 252 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*422 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 256 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*460 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 260 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*499 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 264 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*537 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 268 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*576 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 272 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*614 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 276 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*652 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 280 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*691 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 284 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*729 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 288 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*768 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 292 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*806 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 296 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*844 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 300 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*883 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 304 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*921 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 308 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*960 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 312 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*998 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 316 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1036 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 320 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1075 MHz?GPUUV3erista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/gpu_custom_erista_no_auto.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 324 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'
