;title='HOC Toolkit'
;version=2.0.0
;creator='ppkantorski, B3711, NaGa'
;about='Designed for advanced OC configurations. Use with caution and proper guidance.'
;color=green
;show_widget=true

[@Settings]

[RAM]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
json_file './json/ram_model.json'
'RAM' = '{ram_vendor} {json_file(0,{ram_model})}'


[*Timings]
;mode=forwarder
package_source './timings.ini'

[*Max Clock?RAMmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 36 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Step Mode]
;mode=option
json_file_source './json/step_mode.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 32 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Max Clock?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 20 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*665 MHz?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 20 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*800 MHz?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 24 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*1065 MHz?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 28 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'


[*VDD2]
;mode=option
;selection_mini=true
json_file_source './json/emc_mem_volt.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 16 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*VDDQ?RAMmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/ram_vddq.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 40 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'


[EMC DVB]
;mode=named_step_trackbar
;unlocked=true
json_file_source './json/emc_dvb_shift.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 44 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/



[HP Mode]
;mode=toggle
on:
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 12 01000000
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
off:
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 12 00000000
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/

[gap]
;mode=table
;background=false
;gap=30

[CPU]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'CPU' = 'Speedo {cpu_speedo}'

[*CPU Table?CPUmariko]
;system=mariko
;mode=option
json_file_source './mariko/cpu_table.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 164 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[Low UV Mode?CPUmariko]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/cpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 156 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[High UV Mode?CPUmariko]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/cpu_uv_high.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 160 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*UV Mode?CPUerista]
;system=erista
;mode=option
json_file_source './erista/cpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 140 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'


[*Max Clock?CPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/cpu_max_clock.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 180 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'


[*Boost Clock?CPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/cpu_boost_clock.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 188 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Boost Clock?CPUerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/cpu_boost_clock.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 184 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'



[*Low Freq Vmin?CPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/cpu_low_vmin.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 168 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*High Freq Vmin?CPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/cpu_high_vmin.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 172 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Vmin?CPUerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/cpu_vmin.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 144 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Voltage Limit?CPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/cpu_max_volt.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 176 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Voltage Limit?CPUerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/cpu_max_volt.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 148 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[CPU Unlock?CPUerista]
;system=erista
;mode=toggle
on:
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 152 01000000
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
off:
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 152 00000000
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/


[gap]
;mode=table
;background=false
;gap=30

[GPU]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'GPU' = 'Speedo {gpu_speedo}'


[*GPU Table?GPUmariko]
;system=mariko
;mode=option
json_file_source './json/gpu_uv_table.json' name
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 200 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*GPU Table?GPUerista]
;system=erista
;mode=option
json_file_source './json/gpu_uv_table.json' name
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 192 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Vmin?GPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/gpu_vmin.json' name
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 204 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Vmax?GPUmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/gpu_vmax.json' name
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 208 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Vmin?GPUerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/gpu_vmin.json' name
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 196 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*Voltage Offset]
;mode=option
;selection_mini=true
json_file_source './json/gpu_offset.json' name
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 212 {json_file_source(*,hex)}
mv ./notifications/hoc-reboot_required_once.notify /config/ultrahand/notifications/
set-footer '{json_file_source(*,name)}'

[*High UV Table]
;mode=forwarder
package_source './gpu_table_high_uv.ini'



[@Tools]

[Tools]
[*Info]
;mode=forwarder
package_source './include/info/info.ini'

[*Backup System]
;mode=forwarder
package_source './include/backup/backup.ini'

[*AMS Settings]
;mode=forwarder
package_source './include/settings/ams_settings.ini'
exec cAMSSettings ./global_cmds.ini

[*hekate Settings]
;mode=forwarder
package_source './include/settings/hekate_settings.ini'


[*Software Update]
;mode=forwarder
package_source './software_update.ini'
exec cStageUpdateMenu ./global_cmds.ini


[Apply Changes]

[*Reboot To]
[*Boot Entry]
ini_file_source /bootloader/hekate_ipl.ini
filter config
reboot boot '{ini_file_source(*)}'
[hekate - ]
reboot HEKATE
[hekate UMS - ]
reboot UMS
