;show_widget=true

[Voltages]

[*Vdd2]
;mode=option
;selection_mini=true
json_file_source './json/emc_mem_volt.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 16 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Vddq?RAMmariko]
;system=mariko
;mode=option
;selection_mini=true
json_file_source './mariko/ram_vddq.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 40 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

