;show_widget=true

[RAM Frequency Editor]

[*665 MHz?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 20 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*800 MHz?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 24 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*1065 MHz?RAMerista]
;system=erista
;mode=option
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 28 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

