;title='HOC Toolkit'
;version='2.0.0  KIP Rev 2'
;creator='ppkantorski, B3711, NaGa, MestreYodaRossi'
;about='This package was designed for advance overclocking configurations with HOC.'
;color=green
;show_widget=true


[Module Info]

[Module Info Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=9
;wrapping_mode=word

hex_file /atmosphere/kips/hoc.kip

'Title'='Horizon OC'
'Version'='{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},0,1)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},1,2)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},2,3)}  KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'
'Creator(s)'='Lightos, Souldbminer, Hanai3bi, NaGaa95, B3711, KazushiMe, RetroNX Team, MasaGratoR, ppkantorski, Dominatorul, ZachyCatGames, TDRR, tetetete-ctrl, SciresM, CTCaer'

[gap]
;mode=table
;background=false
;gap=20

[Update Horizon OC]
;mini=true
try:

delete /config/ultrahand/downloads/hoc/
mkdir /config/ultrahand/downloads/hoc/
download https://github.com/ppkantorski/HOC-Toolkit/raw/refs/heads/main/RELEASE.ini './RELEASE.ini'
ini_file './RELEASE.ini'
download "https://github.com/Horizon-OC/Horizon-OC/releases/download/{ini_file(Release Info,latest_hoc)}/dist.zip" /config/ultrahand/downloads/hoc/
unzip /config/ultrahand/downloads/hoc/dist.zip /config/ultrahand/downloads/hoc/
;cp /config/ultrahand/downloads/hoc/atmosphere/kips/hoc.kip /atmosphere/kips/hoc.kip


[Package Info]

[gap]
;mode=table
;background=false
;gap=20

[Update HOC Toolkit]
;mini=true
try:
delete /config/ultrahand/downloads/hoc_toolkit/
mkdir /config/ultrahand/downloads/hoc_toolkit/
download https://github.com/ppkantorski/HOC-Toolkit/raw/refs/heads/main/RELEASE.ini './RELEASE.ini'
ini_file './RELEASE.ini'
download "https://github.com/ppkantorski/HOC-Toolkit/releases/download{ini_file(Release Info,latest_toolkit)}/hoc-toolkit.zip" /config/ultrahand/downloads/hoc_toolkit/
unzip /config/ultrahand/downloads/hoc/hoc-toolkit.zip ./