;title='HOC Toolkit'
;version='2.0.0'
;creator='ppkantorski, B3711, NaGa'
;about='This package includes the sys-clk-hoc system module and sys-clk overlay.'
;color=green
;show_widget=true
;show_version=true

[@Software Update]

[Software Update]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
hex_file /atmosphere/kips/hoc.kip
'Software Update'='Kip Rev 2KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'

[Update All]
test

[gap]
;mode=table
;background=false
;gap=20


[Update HOC Toolkit]
try:
delete /config/ultrahand/downloads/hoc_toolkit/
mkdir /config/ultrahand/downloads/hoc_toolkit/
download https://github.com/ppkantorski/HOC-Toolkit/raw/refs/heads/main/RELEASE.ini './RELEASE.ini'
ini_file './RELEASE.ini'
download "https://github.com/ppkantorski/HOC-Toolkit/releases/download{ini_file(Release Info,latest_toolkit)}/hoc-toolkit.zip" /config/ultrahand/downloads/hoc_toolkit/
unzip /config/ultrahand/downloads/hoc/hoc-toolkit.zip ./


[Update sys-clk-hoc]
test


[Update Horizon OC]
try:

delete /config/ultrahand/downloads/hoc/
mkdir /config/ultrahand/downloads/hoc/
download https://github.com/ppkantorski/HOC-Toolkit/raw/refs/heads/main/RELEASE.ini './RELEASE.ini'
ini_file './RELEASE.ini'
download "https://github.com/Horizon-OC/Horizon-OC/releases/download/{ini_file(Release Info,latest_hoc)}/dist.zip" /config/ultrahand/downloads/hoc/
unzip /config/ultrahand/downloads/hoc/dist.zip /config/ultrahand/downloads/hoc/
exec backup
cp /config/ultrahand/downloads/hoc/atmosphere/kips/hoc.kip /atmosphere/kips/hoc.kip
exec restore
exit



[@Details]


[OC Toolkit Info]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
hex_file /atmosphere/kips/hoc.kip
'Package Info' = 'KIP Rev 2'

[OC Toolkit Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=0
;wrapping_mode=word
hex_file /atmosphere/kips/hoc.kip

'Title'='HOC Toolkit'
'Version'='{package_version}'
'Credits'='ppkantorski, B3711, NaGa'
'About'='Designed for advanced OC configurations. Use with caution and proper guidance.'


[gap]
;mode=table
;background=false
;gap=30


[Module Info]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
hex_file /atmosphere/kips/hoc.kip
'Module Info' = 'KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'


[Module Info Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=0
;wrapping_mode=word
hex_file /atmosphere/kips/hoc.kip

'Title'='Horizon OC'
'Version'='{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},0,1)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},1,2)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},2,3)}  KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'
'Credits'='Lightos, Souldbminer, Hanai3bi, NaGaa95, B3711, KazushiMe, RetroNX Team, MasaGratoR, ppkantorski, Dominatorul, ZachyCatGames, TDRR, tetetete-ctrl, SciresM, CTCaer'
