;title='HOC Toolkit'
;version='2.0.0'
;creator='ppkantorski, B3711, NaGa'
;about='This package includes the sys-clk-hoc system module and sys-clk overlay.'
;color=green
;show_widget=true
;show_version=true

[@Software Update]

[Software Update]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
hex_file /atmosphere/kips/hoc.kip
json '{"2":"","null":""}'
'Software Update'='Kip Rev 2{json({hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})})}'

[Update All?main]
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/hoc-toolkit/
mkdir /config/ultrahand/downloads/hoc-toolkit/
download "https://github.com/ppkantorski/HOC-Toolkit/releases/download/{ini_file(HOC Toolkit,version)}/{ini_file(HOC Toolkit,filename)}" /config/ultrahand/downloads/hoc-toolkit/
unzip /config/ultrahand/downloads/hoc-toolkit/{ini_file(HOC Toolkit,filename)} /
download https://github.com/ppkantorski/Ultrahand-Overlay/releases/latest/download/sdout.zip /config/ultrahand/downloads/hoc-toolkit/
unzip /config/ultrahand/downloads/hoc-toolkit/sdout.zip /
delete /config/ultrahand/downloads/hoc-toolkit/

delete /config/ultrahand/downloads/hoc/
mkdir /config/ultrahand/downloads/hoc/
download "https://github.com/Horizon-OC/Horizon-OC/releases/download/{ini_file(Horizon OC,version)}/{ini_file(Horizon OC,filename)}" /config/ultrahand/downloads/hoc/
unzip /config/ultrahand/downloads/hoc/{ini_file(Horizon OC,filename)} /config/ultrahand/downloads/hoc/
exec cBackupKip ./global_cmds.ini
mv /config/ultrahand/downloads/hoc/atmosphere/kips/hoc.kip /atmosphere/kips/hoc.kip
delete /config/ultrahand/downloads/hoc/
exec cRestoreKip ./global_cmds.ini

delete /config/ultrahand/downloads/sys-clk-hoc/
mkdir /config/ultrahand/downloads/sys-clk-hoc/
download "https://github.com/ppkantorski/Horizon-OC/releases/download/{ini_file(sys-clk-hoc,version)}/{ini_file(sys-clk-hoc,filename)}" /config/ultrahand/sys-clk-hoc/
unzip /config/ultrahand/downloads/sys-clk-hoc/{ini_file(sys-clk-hoc,filename)} /
delete /config/ultrahand/downloads/sys-clk-hoc/

delete /config/ultrahand/downloads/sys-clk/
mkdir /config/ultrahand/downloads/sys-clk/
download "https://github.com/ppkantorski/sys-clk/releases/download/{ini_file(sys-clk,version)}/{ini_file(sys-clk,filename)}" /config/ultrahand/downloads/sys-clk/
mv /config/ultrahand/downloads/sys-clk/{ini_file(sys-clk,filename)} /switch/.overlays/
delete /config/ultrahand/downloads/sys-clk/


delete /config/ultrahand/downloads/Status-Monitor/
mkdir /config/ultrahand/downloads/Status-Monitor/
download "https://github.com/ppkantorski/Status-Monitor-Overlay/releases/download/{ini_file(Status Monitor,version)}/{ini_file(Status Monitor,filename)}" /config/ultrahand/downloads/Status-Monitor/
mv /config/ultrahand/downloads/Status-Monitor/{ini_file(Status Monitor,filename)} /switch/.overlays/
delete /config/ultrahand/downloads/Status-Monitor/


cp ./notifications/hoc-reboot_required.notify /config/ultrahand/notifications/
exit


[gap]
;mode=table
;background=false
;gap=10


[HOC Toolkit]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/hoc-toolkit/
mkdir /config/ultrahand/downloads/hoc-toolkit/
download "https://github.com/ppkantorski/HOC-Toolkit/releases/download/{ini_file(HOC Toolkit,version)}/{ini_file(HOC Toolkit,filename)}" /config/ultrahand/downloads/hoc-toolkit/
unzip /config/ultrahand/downloads/hoc-toolkit/{ini_file(HOC Toolkit,filename)} /
download https://github.com/ppkantorski/Ultrahand-Overlay/releases/latest/download/sdout.zip /config/ultrahand/downloads/hoc-toolkit/
unzip /config/ultrahand/downloads/hoc-toolkit/sdout.zip /
delete /config/ultrahand/downloads/hoc-toolkit/
exit

[Horizon OC]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/hoc/
mkdir /config/ultrahand/downloads/hoc/
download "https://github.com/Horizon-OC/Horizon-OC/releases/download/{ini_file(Horizon OC,version)}/{ini_file(Horizon OC,filename)}" /config/ultrahand/downloads/hoc/
unzip /config/ultrahand/downloads/hoc/{ini_file(Horizon OC,filename)} /config/ultrahand/downloads/hoc/
exec cBackupKip ./global_cmds.ini
mv /config/ultrahand/downloads/hoc/atmosphere/kips/hoc.kip /atmosphere/kips/hoc.kip
delete /config/ultrahand/downloads/hoc/
exec cRestoreKip ./global_cmds.ini

exec boot
cp ./notifications/hoc-reboot_required.notify /config/ultrahand/notifications/

[sys-clk-hoc]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/sys-clk-hoc/
mkdir /config/ultrahand/downloads/sys-clk-hoc/
download "https://github.com/ppkantorski/Horizon-OC/releases/download/{ini_file(sys-clk-hoc,version)}/{ini_file(sys-clk-hoc,filename)}" /config/ultrahand/sys-clk-hoc/
unzip /config/ultrahand/downloads/sys-clk-hoc/{ini_file(sys-clk-hoc,filename)} /
delete /config/ultrahand/downloads/sys-clk-hoc/

[sys-clk]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/sys-clk/
mkdir /config/ultrahand/downloads/sys-clk/
download "https://github.com/ppkantorski/sys-clk/releases/download/{ini_file(sys-clk,version)}/{ini_file(sys-clk,filename)}" /config/ultrahand/downloads/sys-clk/
mv /config/ultrahand/downloads/sys-clk/{ini_file(sys-clk,filename)} /switch/.overlays/
delete /config/ultrahand/downloads/sys-clk/

[Status Monitor]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/Status-Monitor/
mkdir /config/ultrahand/downloads/Status-Monitor/
download "https://github.com/ppkantorski/Status-Monitor-Overlay/releases/download/v{ini_file(Status Monitor,version)}/{ini_file(Status Monitor,filename)}" /config/ultrahand/downloads/Status-Monitor/
mv /config/ultrahand/downloads/Status-Monitor/{ini_file(Status Monitor,filename)} /switch/.overlays/
delete /config/ultrahand/downloads/Status-Monitor/


[gap]
;mode=table
;background=false
;gap=30

[System Update]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'System Update'='HOS {hos_version}AMS {ams_version}'

[Update All?system]
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/Atmosphere/
mkdir /config/ultrahand/downloads/Atmosphere/
download "https://github.com/Atmosphere-NX/Atmosphere/releases/download/{ini_file(Atmosphere,version)}/{ini_file(Atmosphere,filename)}" /config/ultrahand/downloads/Atmosphere/
unzip /config/ultrahand/downloads/Atmosphere/{ini_file(Atmosphere,filename)} /config/ultrahand/downloads/Atmosphere/
mv /config/ultrahand/downloads/Atmosphere/atmosphere/package3 /atmosphere/package3
mv /config/ultrahand/downloads/Atmosphere/atmosphere/reboot_payload.bin /atmosphere/reboot_payload.bin
mv /config/ultrahand/downloads/Atmosphere/atmosphere/stratosphere.romfs /atmosphere/stratosphere.romfs
delete /config/ultrahand/downloads/Atmosphere/

delete /config/ultrahand/downloads/hekate/
mkdir /config/ultrahand/downloads/hekate/
download "https://github.com/ctcaer/hekate/releases/download/v{ini_file(hekate,version)}/{ini_file(hekate,filename)}" /config/ultrahand/downloads/hekate/
unzip /config/ultrahand/downloads/hekate/{ini_file(hekate,filename)} /config/ultrahand/downloads/hekate/
mv /config/ultrahand/downloads/hekate/bootloader/sys/ /bootloader/sys/
mv /config/ultrahand/downloads/hekate/bootloader/update.bin /bootloader/
delete /config/ultrahand/downloads/hekate/

cp ./notifications/hoc-reboot_required.notify /config/ultrahand/notifications/


[gap]
;mode=table
;background=false
;gap=8

[Atmosphere]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/Atmosphere/
mkdir /config/ultrahand/downloads/Atmosphere/
download "https://github.com/Atmosphere-NX/Atmosphere/releases/download/{ini_file(Atmosphere,version)}/{ini_file(Atmosphere,filename)}" /config/ultrahand/downloads/Atmosphere/
unzip /config/ultrahand/downloads/Atmosphere/{ini_file(Atmosphere,filename)} /config/ultrahand/downloads/Atmosphere/
mv /config/ultrahand/downloads/Atmosphere/atmosphere/package3 /atmosphere/package3
mv /config/ultrahand/downloads/Atmosphere/atmosphere/reboot_payload.bin /atmosphere/reboot_payload.bin
mv /config/ultrahand/downloads/Atmosphere/atmosphere/stratosphere.romfs /atmosphere/stratosphere.romfs
delete /config/ultrahand/downloads/Atmosphere/

cp ./notifications/hoc-reboot_required.notify /config/ultrahand/notifications/

[hekate]
;mini=true
try:
delete './RELEASE.ini'
download https://raw.githubusercontent.com/ppkantorski/HOC-Toolkit/refs/heads/main/RELEASE.ini './RELEASE.ini'
path_exists './RELEASE.ini'
ini_file './RELEASE.ini'

delete /config/ultrahand/downloads/hekate/
mkdir /config/ultrahand/downloads/hekate/
download "https://github.com/ctcaer/hekate/releases/download/v{ini_file(hekate,version)}/{ini_file(hekate,filename)}" /config/ultrahand/downloads/hekate/
unzip /config/ultrahand/downloads/hekate/{ini_file(hekate,filename)} /config/ultrahand/downloads/hekate/
mv /config/ultrahand/downloads/hekate/bootloader/sys/ /bootloader/sys/
mv /config/ultrahand/downloads/hekate/bootloader/update.bin /bootloader/
delete /config/ultrahand/downloads/hekate/

cp ./notifications/hoc-reboot_required.notify /config/ultrahand/notifications/


[@Details]

[OC Toolkit Info]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
hex_file /atmosphere/kips/hoc.kip
'Package Info' = 'KIP Rev 2'

[OC Toolkit Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=0
;wrapping_mode=word
hex_file /atmosphere/kips/hoc.kip

'Title'='HOC Toolkit'
'Version'='{package_version}'
'Credits'='ppkantorski, B3711, NaGa'
'About'='Designed for advanced OC configurations. Use with caution and proper guidance.'


[gap]
;mode=table
;background=false
;gap=30


[Module Info]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
hex_file /atmosphere/kips/hoc.kip
'Module Info' = 'KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'


[Module Info Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=0
;wrapping_mode=word
hex_file /atmosphere/kips/hoc.kip

'Title'='Horizon OC'
'Version'='{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},0,1)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},1,2)}.{slice({hex_to_decimal({hex_to_rhex({hex_file(CUST,8,4)})})},2,3)}  KIP Rev {hex_to_decimal({hex_to_rhex({hex_file(CUST,4,4)})})}'
'Credits'='Lightos, Souldbminer, Hanai3bi, NaGaa95, B3711, KazushiMe, RetroNX Team, MasaGratoR, ppkantorski, Dominatorul, ZachyCatGames, TDRR, tetetete-ctrl, SciresM, CTCaer'
