;show_widget=true

[@Primary Timings]
[Timing Presets]
;mode=table
;background=false
;spacing=4
;gap=20
;header_indent=true
;info_text_color=header
;section_text_color=header
'Presets' = 'Choose a RAM vendor profile'

[*Samsung]
;mode=forwarder
package_source './preset_samsung.ini'


[*Micron]
;system=mariko
;mode=forwarder
package_source './preset_micron.ini'


[*Hynix]
;system=mariko
;mode=forwarder
package_source './preset_hynix.ini'


[*Default]
;mode=forwarder
package_source './preset_default.ini'
