;show_widget=true

[@TimingsPage]

[Timings?header]
;mode=table
;polling=true
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
ini_file './config.ini'
'Timings' = '{ini_file(*Timings,footer)}'

[*T1 tRCD]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t1_trcd.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 52 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T2 tRP]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t1_trcd.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 56 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T3 tRAS]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t3_tras.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 60 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T4 tRRD/tFAW?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/mariko_t4_trrd.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 64 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T4 tRRD/tFAW?RAMerista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t4_trrd.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 64 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T5 tRFC]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t5_trfc.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 68 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T6 tRTW]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t6_trtw.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 72 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T7 tWTR]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t6_trtw.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 76 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T8 tREFI]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t8_trefi.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 80 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings


[*Presets]
;mode=forwarder
package_source './include/ram/timing_presets.ini'

[gap]
;mode=table
;background=false
;gap=20


[*Timings TBreak]

[*Min Clock]
;mode=option
;selection_mini=true
json_file_source './json/timing_tbreak.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 88 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[gap]
;mode=table
;background=false
;gap=20

[*T2 RP Cap 1333WL]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t2_trp_cap.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 84 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T6 tRTW Low]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/low_t6_trtw.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 92 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T7 tWTR Low]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/low_t7_twtr.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 96 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T6 tRTW Fine Tune]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t6_trtw_fine_tune.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 424 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[*T7 tWTR Fine Tune]
;mode=option
;mini=true
;selection_mini=true
json_file_source './json/t7_twtr_fine_tune.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 428 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
exec cUpdateTimings

[Latency]

[*Read Latency?RAMmariko]
;system=mariko
;mode=option
;mini=true
json_file_source './json/mariko_read_latency.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 132 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Write Latency?RAMmariko]
;system=mariko
;mode=option
;mini=true
json_file_source './json/mariko_write_latency.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 136 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Read Latency?RAMerista]
;system=erista
;mode=option
;mini=true
json_file_source './json/read_latency.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 132 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Write Latency?RAMerista]
;system=erista
;mode=option
;mini=true
json_file_source './json/write_latency.json' label
hex-by-custom-offset /atmosphere/kips/hoc.kip CUST 136 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Advanced Latency?RAMmariko]
;system=mariko
;mode=forwarder
package_source './advanced_ram_latency.ini'
