;show_widget=true

[@Configure]

[hekate Settings]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'hekate Settings'='hekate {hekate_version}'


[*Bootloader INI]
;mode=option
file_source '/bootloader/hekate_ipl.ini'
file_source '/bootloader/ini/*.ini'
filter '/bootloader/ini/hekate_ipl.ini'

set-footer '{file_name}'
set-ini-val './config.ini' '*Bootloader INI' 'ini_path' '{file_source}'
back


[*Patch Type]
;mode=option
;footer=hoc.kip
;footer_highlight=true

ini_file ./config.ini
list_source '("hoc.kip","exosphere.bin")'
set-footer '{list_source(*)}'

ini_file ./config.ini
json '{"hoc.kip":"kip1","exosphere.bin":"secmon"}'
set-ini-val './config.ini' 'Patch All' 'footer' '{json({list_source(*)})}'
set-ini-val './config.ini' 'Remove All' 'footer' '{json({list_source(*)})}'

refresh-return
back
'{if_==({json({list_source(*)})},secmon,notify,pass)}' "AOTAG (optional)" "HOC Toolkit" hoc


[gap]
;mode=table
;background=false
;gap=12


[Patch All]
;footer=kip1
;footer_highlight=true
ini_file './config.ini'

try:
path_exists '{ini_file("*Bootloader INI",ini_path)}'


json '{"hoc.kip":"kip1","exosphere.bin":"secmon"}'
set-ini-val ./config.ini "Patch All" patch_key '{json({ini_file(*Patch Type,footer)})}'

json '{"hoc.kip":"atmosphere/kips/hoc.kip","exosphere.bin":"atmosphere/hoc/exosphere.bin"}'
set-ini-val ./config.ini "Patch All" patch_value '{json({ini_file(*Patch Type,footer)})}'

ini_file './config.ini'

set-ini-val-matching-key '{ini_file("*Bootloader INI",ini_path)}' 'pkg3' '{ini_file(Patch All,patch_key)}' '{ini_file(Patch All,patch_value)}'
set-ini-val-matching-key '{ini_file("*Bootloader INI",ini_path)}' 'fss0' '{ini_file(Patch All,patch_key)}' '{ini_file(Patch All,patch_value)}'
cp ./../../notifications/hoc-reboot_required.notify /config/ultrahand/notifications/

try:
notify-now "Select a bootloader ini." "HOC Toolkit" hoc
path_exists '{ini_file("*Bootloader INI",ini_path)}'


[Remove All]
;footer=kip1
;footer_highlight=true
ini_file './config.ini'
try:
path_exists '{ini_file("*Bootloader INI",ini_path)}'
json '{"hoc.kip":"kip1","exosphere.bin":"secmon"}'
remove-ini-key-matching-key '{ini_file("*Bootloader INI",ini_path)}' 'pkg3' '{json({ini_file(*Patch Type,footer)})}'
remove-ini-key-matching-key '{ini_file("*Bootloader INI",ini_path)}' 'fss0' '{json({ini_file(*Patch Type,footer)})}'
cp ./../../notifications/hoc-reboot_required.notify /config/ultrahand/notifications/

try:
notify-now "Select a bootloader ini." "HOC Toolkit" hoc
path_exists '{ini_file("*Bootloader INI",ini_path)}'

[gap]
;mode=table
;background=false
;gap=12

[*Patch Entry]
ini_file './config.ini'
ini_file_source '{ini_file("*Bootloader INI",ini_path)}'
filter config

try:
path_exists '{ini_file("*Bootloader INI",ini_path)}'

json '{"hoc.kip":"kip1","exosphere.bin":"secmon"}'
set-ini-val ./config.ini "*Patch Entry" patch_key '{json({ini_file(*Patch Type,footer)})}'

json '{"hoc.kip":"atmosphere/kips/hoc.kip","exosphere.bin":"atmosphere/hoc/exosphere.bin"}'
set-ini-val ./config.ini "*Patch Entry" patch_value '{json({ini_file(*Patch Type,footer)})}'

ini_file './config.ini'

set-ini-val '{ini_file("*Bootloader INI",ini_path)}' '{ini_file_source(*)}' '{ini_file(*Patch Entry,patch_key)}' '{ini_file(*Patch Entry,patch_value)}'
cp ./../../notifications/hoc-reboot_required.notify /config/ultrahand/notifications/


[*Remove Entry]
ini_file './config.ini'
ini_file_source '{ini_file("*Bootloader INI",ini_path)}'
filter config
try:
path_exists '{ini_file("*Bootloader INI",ini_path)}'
json '{"hoc.kip":"kip1","exosphere.bin":"secmon"}'
remove-ini-key '{ini_file("*Bootloader INI",ini_path)}' '{ini_file_source(*)}' '{json({ini_file(*Patch Type,footer)})}'
cp ./../../notifications/hoc-reboot_required.notify /config/ultrahand/notifications/



[@View INI]

[Bootloader INI Header]
;mode=table
;background=false
;spacing=4
;gap=20
;header_indent=true
;section_text_color=header
;info_text_color=section
ini_file './config.ini'
json '{"null.ini":"Not available", "{ini_file(*Bootloader INI,footer)}.ini":"{ini_file(*Bootloader INI,footer)}.ini"}'
'{json({ini_file(*Bootloader INI,footer)}.ini)}'='Bootloader INI'

[Bootloader INI Table]
;mode=table
;wrapping_mode=char
;wrapping_indent=true
;spacing=4
ini_file './config.ini'
list_file_source '{ini_file("*Bootloader INI",ini_path)}'
