;show_widget=true

[@Configure]
[HOC Settings]

[hoc-clk Persistence]
;mode=toggle?on
;progress=true
on:
exec cPatchHOCCLK ./../../global_cmds.ini
touch ./../../flags/UPDATE_HOC_CONFIG.flag
off:
delete ./../../flags/UPDATE_HOC_CONFIG.flag


[gap]
;system=mariko
;mode=table
;background=false
;gap=6

[hoc-clk Persistence Info]
;mode=table
;background=false
;info_text_color=on_value
;spacing=4
;gap=15
'' = '  Keep HOC config.ini updated.'


[gap]
;system=mariko
;mode=table
;background=false
;gap=10

[sys-clk-hoc  hoc-clk]
;mode=toggle?off
on:
try:
path_exists './../../data/horizon-oc/atmosphere/contents/00FF0000636C6BFF/'
cp './../../data/horizon-oc/atmosphere/contents/00FF0000636C6BFF/' /atmosphere/contents/00FF0000636C6BFF/
delete /switch/.overlays/sys-clk-overlay.ovl
cp './../../data/horizon-oc/switch/.overlays/horizon-oc-overlay.ovl' /switch/.overlays/
delete /config/horizon-oc/lang/
mkdir /config/horizon-oc/lang/
cp './../../data/horizon-oc/config/horizon-oc/lang/*.json' /config/horizon-oc/lang/
ini_file /config/ultrahand/overlays.ini
set-ini-val /config/ultrahand/overlays.ini 'horizon-oc-overlay.ovl' key_combo "{ini_file(sys-clk-overlay.ovl,key_combo)}"
set-ini-val /config/ultrahand/overlays.ini 'sys-clk-overlay.ovl' key_combo ''
refresh combos
touch './../../flags/USING_HOC_CLK.flag'

off:

try:
path_exists './../../data/sys-clk-hoc/atmosphere/contents/00FF0000636C6BFF/'
cp './../../data/sys-clk-hoc/atmosphere/contents/00FF0000636C6BFF/' /atmosphere/contents/00FF0000636C6BFF/
delete /switch/.overlays/horizon-oc-overlay.ovl
cp './../../data/sys-clk-hoc/switch/.overlays/sys-clk-overlay.ovl' /switch/.overlays/
mkdir /config/sys-clk/lang/
cp './../../data/sys-clk-hoc/config/sys-clk/lang/' /config/sys-clk/lang/
ini_file /config/ultrahand/overlays.ini
set-ini-val /config/ultrahand/overlays.ini 'sys-clk-overlay.ovl' key_combo "{ini_file(horizon-oc-overlay.ovl,key_combo)}"
set-ini-val /config/ultrahand/overlays.ini 'horizon-oc-overlay.ovl' key_combo ''
refresh combos
delete './../../flags/USING_HOC_CLK.flag'


[gap]
;system=mariko
;mode=table
;background=false
;gap=6

[Module Toggle Info]
;mode=table
;background=false
;info_text_color=on_value
;spacing=4
;gap=15
'' = '  Swap between modules.'


[gap]
;system=mariko
;mode=table
;background=false
;gap=10


[Open Sysmodules]
try:
path_exists /switch/.overlays/ovlSysmodules.ovl
open /switch/.overlays/ovlSysmodules.ovl


[gap]
;system=mariko
;mode=table
;background=false
;gap=6

[Sysmodules Info]
;mode=table
;background=false
;info_text_color=on_value
;spacing=4
;gap=15
'' = '  Ensure off before swapping.'

[gap]
;system=mariko
;mode=table
;background=false
;gap=10



[Notice]
[Notice Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=20
;wrapping_mode=auto
;section_text_color=warning
'Users must first disable sys-clk-hoc / hoc-clk in Sysmodules before clicking the “sys-clk-hoc  hoc-clk” toggle.'



[@View INI]

[/config/horizon-oc/config.ini]

[HOC Config INI Table]
;mode=table
;wrapping_mode=char
;wrapping_indent=true
;spacing=4
list_file_source '/config/horizon-oc/config.ini'