;show_widget=true

[@Primary Timings]
[Timing Presets]
;mode=table
;background=false
;spacing=4
;gap=20
;header_indent=true
;info_text_color=section
;section_text_color=header
json_file './../../json/ram_model.json'
'Presets' = '{ram_vendor} {json_file(0,{ram_model})}'


[*Default]
;mode=forwarder
package_source './preset_default.ini'


[*Samsung]
;mode=forwarder
package_source './preset_samsung.ini'


[*Micron]
;system=mariko
;mode=forwarder
package_source './preset_micron.ini'


[*Hynix]
;system=mariko
;mode=forwarder
package_source './preset_hynix.ini'
