;show_widget=true

[@Main Presets]
[RAM]
[RAM Table]
;mode=table
;spacing=4
;gap=32
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
'Timings' = {ini_file(Backup,Timings)}

mariko:
json_file './../../json/frequency_lookup.json'
'RAM Clock' = '{json_file(0,{ini_file(Backup,ramMHzM)})} (△{json_file(1,{ini_file(Backup,ramStepMode)})})'
json_file './../../json/emc_mem_volt_lookup.json'
'VDD2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
json_file './../../mariko/ram_vddq_lookup.json'
'VDDQ' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './../../json/emc_dvb_shift_lookup.json'
'DVB Shift' = {json_file(0,{ini_file(Backup,socDvbShift)})}
json_file './../../mariko/soc_vmax_lookup.json'
'SOC Max Volt' = {json_file(0,{ini_file(Backup,socVmaxM)})}
json '[{"00000000":"Off", "01000000":"On"}]'
'HP Mode' = {json(0,{ini_file(Backup,hpMode)})}


erista:
json_file './../../json/emc_mem_volt_lookup.json'
'VDD2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
json_file './../../json/emc_dvb_shift_lookup.json'
'DVB Shift' = {json_file(0,{ini_file(Backup,socDvbShift)})}
json '[{"00000000":"Off", "01000000":"On"}]'
'HP Mode' = {json(0,{ini_file(Backup,hpMode)})}
json_file './../../json/frequency_lookup.json'
'665 MHz' = {json_file(0,{ini_file(Backup,ramMHzE665)})}

[CPU]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'CPU' = ''

[CPU Table]
;mode=table
;spacing=4
;gap=32
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
mariko:
json_file './../../mariko/cpu_table_lookup.json'
'CPU Table' = {json_file(0,{ini_file(Backup,cpuTableM)})}
json_file './../../mariko/cpu_uv_lookup.json'
'Low UV' = {json_file(0,{ini_file(Backup,cpuUvM)})}
json_file './../../mariko/cpu_uv_high_lookup.json'
'High UV' = {json_file(0,{ini_file(Backup,cpuUvHighM)})}
json_file './../../json/frequency_lookup.json'
'Max Clock' = {json_file(0,{ini_file(Backup,cpuMaxClockM)})}
'Boost Clock' = {json_file(0,{ini_file(Backup,cpuBoostM)})}
json_file './../../json/cpu_vmin_lookup.json'
'Low Vmin' = {json_file(0,{ini_file(Backup,cpuVminLowM)})}
'High Vmin' = {json_file(0,{ini_file(Backup,cpuVminHighM)})}
json_file './../../json/cpu_max_volt_lookup.json'
'Volt Limit' = {json_file(0,{ini_file(Backup,cpuVoltLimitM)})}
erista:
json_file './../../erista/cpu_uv_lookup.json'
'UV' = {json_file(0,{ini_file(Backup,cpuUvE)})}
json_file './../../json/cpu_vmin_lookup.json'
'Vmin' = {json_file(0,{ini_file(Backup,cpuVminE)})}
json_file './../../json/cpu_max_volt_lookup.json'
'Volt Limit' = {json_file(0,{ini_file(Backup,cpuVoltLimitE)})}
json_file './../../json/frequency_lookup.json'
'Boost Clock' = {json_file(0,{ini_file(Backup,cpuBoostE)})}
json '[{"00000000":"Off", "01000000":"On"}]'
'CPU Unlock' = {json(0,{ini_file(Backup,cpuUnlockE)})}

[GPU]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'GPU' = ''

[GPU Table]
;mode=table
;spacing=4
;gap=12
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'

mariko:
json_file './../../json/gpu_uv_table_lookup.json'
'GPU Table' = {json_file(0,{ini_file(Backup,gpuUvM)})}
json_file './../../json/gpu_volt_lookup.json'
'Vmin' = {json_file(0,{ini_file(Backup,gpuVminM)})}
'Vmax' = {json_file(0,{ini_file(Backup,gpuVmaxM)})}
json_file './../../json/gpu_offset_lookup.json'
'Voltage Offset' = {json_file(0,{ini_file(Backup,gpuOffset)})}

erista:
json_file './../../json/gpu_uv_table_lookup.json'
'GPU Table' = {json_file(0,{ini_file(Backup,gpuUvE)})}
json_file './../../json/gpu_volt_lookup.json'
'Vmin' = {json_file(0,{ini_file(Backup,gpuVminE)})}
json_file './../../json/gpu_offset_lookup.json'
'Voltage Offset' = {json_file(0,{ini_file(Backup,gpuOffset)})}


[@More Info]
[Advanced RAM]

[Advanced RAM Latency Table]
;system=mariko
;mode=table
;spacing=4
;gap=28
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
 
json_file './../../json/latency_freq_lookup.json'
'1333 Latency Max' = {json_file(0,{ini_file(Backup,ramReadLatency0)})}{json_file(0,{ini_file(Backup,ramWriteLatency0)})}
'1600 Latency Max' = {json_file(0,{ini_file(Backup,ramReadLatency1)})}{json_file(0,{ini_file(Backup,ramWriteLatency1)})}
'1866 Latency Max' = {json_file(0,{ini_file(Backup,ramReadLatency2)})}{json_file(0,{ini_file(Backup,ramWriteLatency2)})}
'2133 Latency Max' = {json_file(0,{ini_file(Backup,ramReadLatency3)})}{json_file(0,{ini_file(Backup,ramWriteLatency3)})}

[Advanced RAM TBreak Table]
;mode=table
;spacing=4
;gap=32
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'

json_file './../../json/timing_tbreak_lookup.json'
'TBreak' = {json_file(0,{ini_file(Backup,TBreak)})}
json_file './../../json/t2_trp_cap_lookup.json'
'T2 RP Cap 1333WL' = {json_file(0,{ini_file(Backup,T2RpCap)})}
json_file './../../json/low_t6_trtw_lookup.json'
'T6 tRTW Low' = {json_file(0,{ini_file(Backup,LowT6)})}
json_file './../../json/t6_trtw_fine_tune_lookup.json'
'T6 tRTW Fine' = {json_file(0,{ini_file(Backup,T6FineTune)})}
json_file './../../json/low_t7_twtr_lookup.json'
'T7 tWTR Low' = {json_file(0,{ini_file(Backup,LowT7)})}
json_file './../../json/t7_twtr_fine_tune_lookup.json'
'T7 tWTR Fine' = {json_file(0,{ini_file(Backup,T7FineTune)})}

[SOC Table Voltage]
;system=mariko
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'SOC Table' = 'Voltage'

[SOC Voltage Table]
;system=mariko
;mode=table
;spacing=4
;gap=32
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
json_file './../../mariko/soc_volt_lookup.json'
json '{"Do not override":";","null":""}'

{json({json_file(0,{ini_file(Backup,socVolt1866)})})}'1866 MHz' = {json_file(0,{ini_file(Backup,socVolt1866)})}
{json({json_file(0,{ini_file(Backup,socVolt2000)})})}'2000 MHz' = {json_file(0,{ini_file(Backup,socVolt2000)})}
{json({json_file(0,{ini_file(Backup,socVolt2133)})})}'2133 MHz' = {json_file(0,{ini_file(Backup,socVolt2133)})}
{json({json_file(0,{ini_file(Backup,socVolt2200)})})}'2200 MHz' = {json_file(0,{ini_file(Backup,socVolt2200)})}
{json({json_file(0,{ini_file(Backup,socVolt2266)})})}'2266 MHz' = {json_file(0,{ini_file(Backup,socVolt2266)})}
{json({json_file(0,{ini_file(Backup,socVolt2333)})})}'2333 MHz' = {json_file(0,{ini_file(Backup,socVolt2333)})}
{json({json_file(0,{ini_file(Backup,socVolt2400)})})}'2400 MHz' = {json_file(0,{ini_file(Backup,socVolt2400)})}
{json({json_file(0,{ini_file(Backup,socVolt2433)})})}'2433 MHz' = {json_file(0,{ini_file(Backup,socVolt2433)})}
{json({json_file(0,{ini_file(Backup,socVolt2466)})})}'2466 MHz' = {json_file(0,{ini_file(Backup,socVolt2466)})}
{json({json_file(0,{ini_file(Backup,socVolt2533)})})}'2533 MHz' = {json_file(0,{ini_file(Backup,socVolt2533)})}
{json({json_file(0,{ini_file(Backup,socVolt2566)})})}'2566 MHz' = {json_file(0,{ini_file(Backup,socVolt2566)})}
{json({json_file(0,{ini_file(Backup,socVolt2600)})})}'2600 MHz' = {json_file(0,{ini_file(Backup,socVolt2600)})}
{json({json_file(0,{ini_file(Backup,socVolt2666)})})}'2666 MHz' = {json_file(0,{ini_file(Backup,socVolt2666)})}
{json({json_file(0,{ini_file(Backup,socVolt2700)})})}'2700 MHz' = {json_file(0,{ini_file(Backup,socVolt2700)})}
{json({json_file(0,{ini_file(Backup,socVolt2733)})})}'2733 MHz' = {json_file(0,{ini_file(Backup,socVolt2733)})}
{json({json_file(0,{ini_file(Backup,socVolt2766)})})}'2766 MHz' = {json_file(0,{ini_file(Backup,socVolt2766)})}
{json({json_file(0,{ini_file(Backup,socVolt2800)})})}'2800 MHz' = {json_file(0,{ini_file(Backup,socVolt2800)})}
{json({json_file(0,{ini_file(Backup,socVolt2833)})})}'2833 MHz' = {json_file(0,{ini_file(Backup,socVolt2833)})}
{json({json_file(0,{ini_file(Backup,socVolt2900)})})}'2900 MHz' = {json_file(0,{ini_file(Backup,socVolt2900)})}
{json({json_file(0,{ini_file(Backup,socVolt2933)})})}'2933 MHz' = {json_file(0,{ini_file(Backup,socVolt2933)})}
{json({json_file(0,{ini_file(Backup,socVolt3000)})})}'3000 MHz' = {json_file(0,{ini_file(Backup,socVolt3000)})}
{json({json_file(0,{ini_file(Backup,socVolt3033)})})}'3033 MHz' = {json_file(0,{ini_file(Backup,socVolt3033)})}
{json({json_file(0,{ini_file(Backup,socVolt3100)})})}'3100 MHz' = {json_file(0,{ini_file(Backup,socVolt3100)})}
{json({json_file(0,{ini_file(Backup,socVolt3133)})})}'3133 MHz' = {json_file(0,{ini_file(Backup,socVolt3133)})}
{json({json_file(0,{ini_file(Backup,socVolt3166)})})}'3166 MHz' = {json_file(0,{ini_file(Backup,socVolt3166)})}
{json({json_file(0,{ini_file(Backup,socVolt3200)})})}'3200 MHz' = {json_file(0,{ini_file(Backup,socVolt3200)})}

[GPU Table High UV]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'GPU Table' = 'High UV'

[High UV Table]
;mode=table
;spacing=4
;gap=12
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
json '{"Disabled":";","null":""}'
mariko:
json_file './../../json/gpu_custom_mariko_lookup.json'
{json({json_file(0,{ini_file(Backup,m76Uv3)})})}'76 MHz'    = {json_file(0,{ini_file(Backup,m76Uv3)})}
{json({json_file(0,{ini_file(Backup,m153Uv3)})})}'153 MHz'  = {json_file(0,{ini_file(Backup,m153Uv3)})}
{json({json_file(0,{ini_file(Backup,m230Uv3)})})}'230 MHz'  = {json_file(0,{ini_file(Backup,m230Uv3)})}
{json({json_file(0,{ini_file(Backup,m307Uv3)})})}'307 MHz'  = {json_file(0,{ini_file(Backup,m307Uv3)})}
{json({json_file(0,{ini_file(Backup,m384Uv3)})})}'384 MHz'  = {json_file(0,{ini_file(Backup,m384Uv3)})}
{json({json_file(0,{ini_file(Backup,m460Uv3)})})}'460 MHz'  = {json_file(0,{ini_file(Backup,m460Uv3)})}
{json({json_file(0,{ini_file(Backup,m537Uv3)})})}'537 MHz'  = {json_file(0,{ini_file(Backup,m537Uv3)})}
{json({json_file(0,{ini_file(Backup,m614Uv3)})})}'614 MHz'  = {json_file(0,{ini_file(Backup,m614Uv3)})}
{json({json_file(0,{ini_file(Backup,m691Uv3)})})}'691 MHz'  = {json_file(0,{ini_file(Backup,m691Uv3)})}
{json({json_file(0,{ini_file(Backup,m768Uv3)})})}'768 MHz'  = {json_file(0,{ini_file(Backup,m768Uv3)})}
{json({json_file(0,{ini_file(Backup,m844Uv3)})})}'844 MHz'  = {json_file(0,{ini_file(Backup,m844Uv3)})}
{json({json_file(0,{ini_file(Backup,m921Uv3)})})}'921 MHz'  = {json_file(0,{ini_file(Backup,m921Uv3)})}
{json({json_file(0,{ini_file(Backup,m998Uv3)})})}'998 MHz'  = {json_file(0,{ini_file(Backup,m998Uv3)})}
{json({json_file(0,{ini_file(Backup,m1075Uv3)})})}'1075 MHz' = {json_file(0,{ini_file(Backup,m1075Uv3)})}
{json({json_file(0,{ini_file(Backup,m1152Uv3)})})}'1152 MHz' = {json_file(0,{ini_file(Backup,m1152Uv3)})}
{json({json_file(0,{ini_file(Backup,m1228Uv3)})})}'1228 MHz' = {json_file(0,{ini_file(Backup,m1228Uv3)})}

json_file './../../json/gpu_custom_mariko_no_auto_lookup.json'
{json({json_file(0,{ini_file(Backup,m1267Uv3)})})}'1267 MHz' = {json_file(0,{ini_file(Backup,m1267Uv3)})}
{json({json_file(0,{ini_file(Backup,m1305Uv3)})})}'1305 MHz' = {json_file(0,{ini_file(Backup,m1305Uv3)})}
{json({json_file(0,{ini_file(Backup,m1344Uv3)})})}'1344 MHz' = {json_file(0,{ini_file(Backup,m1344Uv3)})}
{json({json_file(0,{ini_file(Backup,m1382Uv3)})})}'1382 MHz' = {json_file(0,{ini_file(Backup,m1382Uv3)})}
{json({json_file(0,{ini_file(Backup,m1420Uv3)})})}'1420 MHz' = {json_file(0,{ini_file(Backup,m1420Uv3)})}
{json({json_file(0,{ini_file(Backup,m1459Uv3)})})}'1459 MHz' = {json_file(0,{ini_file(Backup,m1459Uv3)})}
{json({json_file(0,{ini_file(Backup,m1497Uv3)})})}'1497 MHz' = {json_file(0,{ini_file(Backup,m1497Uv3)})}
{json({json_file(0,{ini_file(Backup,m1536Uv3)})})}'1536 MHz' = {json_file(0,{ini_file(Backup,m1536Uv3)})}

erista:
json_file './../../json/gpu_custom_erista_lookup.json'
{json({json_file(0,{ini_file(Backup,e76Uv3)})})}'76 MHz'  = {json_file(0,{ini_file(Backup,e76Uv3)})}
{json({json_file(0,{ini_file(Backup,e115Uv3)})})}'115 MHz' = {json_file(0,{ini_file(Backup,e115Uv3)})}
{json({json_file(0,{ini_file(Backup,e153Uv3)})})}'153 MHz' = {json_file(0,{ini_file(Backup,e153Uv3)})}
{json({json_file(0,{ini_file(Backup,e192Uv3)})})}'192 MHz' = {json_file(0,{ini_file(Backup,e192Uv3)})}
{json({json_file(0,{ini_file(Backup,e230Uv3)})})}'230 MHz' = {json_file(0,{ini_file(Backup,e230Uv3)})}
{json({json_file(0,{ini_file(Backup,e269Uv3)})})}'269 MHz' = {json_file(0,{ini_file(Backup,e269Uv3)})}
{json({json_file(0,{ini_file(Backup,e307Uv3)})})}'307 MHz' = {json_file(0,{ini_file(Backup,e307Uv3)})}
{json({json_file(0,{ini_file(Backup,e346Uv3)})})}'346 MHz' = {json_file(0,{ini_file(Backup,e346Uv3)})}
{json({json_file(0,{ini_file(Backup,e384Uv3)})})}'384 MHz' = {json_file(0,{ini_file(Backup,e384Uv3)})}
{json({json_file(0,{ini_file(Backup,e422Uv3)})})}'422 MHz' = {json_file(0,{ini_file(Backup,e422Uv3)})}
{json({json_file(0,{ini_file(Backup,e460Uv3)})})}'460 MHz' = {json_file(0,{ini_file(Backup,e460Uv3)})}
{json({json_file(0,{ini_file(Backup,e499Uv3)})})}'499 MHz' = {json_file(0,{ini_file(Backup,e499Uv3)})}
{json({json_file(0,{ini_file(Backup,e537Uv3)})})}'537 MHz' = {json_file(0,{ini_file(Backup,e537Uv3)})}
{json({json_file(0,{ini_file(Backup,e576Uv3)})})}'576 MHz' = {json_file(0,{ini_file(Backup,e576Uv3)})}
{json({json_file(0,{ini_file(Backup,e614Uv3)})})}'614 MHz' = {json_file(0,{ini_file(Backup,e614Uv3)})}
{json({json_file(0,{ini_file(Backup,e652Uv3)})})}'652 MHz' = {json_file(0,{ini_file(Backup,e652Uv3)})}
{json({json_file(0,{ini_file(Backup,e691Uv3)})})}'691 MHz' = {json_file(0,{ini_file(Backup,e691Uv3)})}
{json({json_file(0,{ini_file(Backup,e729Uv3)})})}'729 MHz' = {json_file(0,{ini_file(Backup,e729Uv3)})}
{json({json_file(0,{ini_file(Backup,e768Uv3)})})}'768 MHz' = {json_file(0,{ini_file(Backup,e768Uv3)})}
{json({json_file(0,{ini_file(Backup,e806Uv3)})})}'806 MHz' = {json_file(0,{ini_file(Backup,e806Uv3)})}
{json({json_file(0,{ini_file(Backup,e844Uv3)})})}'844 MHz' = {json_file(0,{ini_file(Backup,e844Uv3)})}
{json({json_file(0,{ini_file(Backup,e883Uv3)})})}'883 MHz' = {json_file(0,{ini_file(Backup,e883Uv3)})}
{json({json_file(0,{ini_file(Backup,e921Uv3)})})}'921 MHz' = {json_file(0,{ini_file(Backup,e921Uv3)})}
{json({json_file(0,{ini_file(Backup,e960Uv3)})})}'960 MHz' = {json_file(0,{ini_file(Backup,e960Uv3)})}
{json({json_file(0,{ini_file(Backup,e998Uv3)})})}'998 MHz' = {json_file(0,{ini_file(Backup,e998Uv3)})}
json_file './../../json/gpu_custom_erista_no_auto_lookup.json'
{json({json_file(0,{ini_file(Backup,e1036Uv3)})})}'1036 MHz' = {json_file(0,{ini_file(Backup,e1036Uv3)})}
{json({json_file(0,{ini_file(Backup,e1075Uv3)})})}'1075 MHz' = {json_file(0,{ini_file(Backup,e1075Uv3)})}
