;show_widget=true

[@Main Presets]
[RAM]
[RAM Table]
;mode=table
;spacing=4
;gap=0
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
'Timings' = {ini_file(Backup,Timings)}

mariko:
json_file './../../json/frequency_lookup.json'
'RAM Clock' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './../../json/step_mode_lookup.json'
'Step Mode' = {json_file(0,{ini_file(Backup,ramStepMode)})}
json_file './../../json/emc_mem_volt_lookup.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
json_file './../../mariko/ram_vddq_lookup.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './../../json/soc_dvb_shift_lookup.json'
'SOC DVB' = {json_file(0,{ini_file(Backup,socDvbShift)})}
json '[{"00000000":"Off", "01000000":"On"}]'
'HP Mode' = {json(0,{ini_file(Backup,hpMode)})}
json_file './../../json/latency_freq_lookup.json'
'Latency 0' = {json_file(0,{ini_file(Backup,ramReadLatency0)})}{json_file(0,{ini_file(Backup,ramWriteLatency0)})}
'Latency 1' = {json_file(0,{ini_file(Backup,ramReadLatency1)})}{json_file(0,{ini_file(Backup,ramWriteLatency1)})}
'Latency 2' = {json_file(0,{ini_file(Backup,ramReadLatency2)})}{json_file(0,{ini_file(Backup,ramWriteLatency2)})}
'Latency 3' = {json_file(0,{ini_file(Backup,ramReadLatency3)})}{json_file(0,{ini_file(Backup,ramWriteLatency3)})}
json_file './../../json/frequency_lookup.json'
'Latency' = {json_file(0,{ini_file(Backup,ramReadLat)})}{json_file(0,{ini_file(Backup,ramWriteLat)})}

erista:
json_file './../../json/emc_mem_volt_lookup.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
json_file './../../json/soc_dvb_shift_lookup.json'
'SoC Shift' = {json_file(0,{ini_file(Backup,socDvbShift)})}
json '[{"00000000":"Off", "01000000":"On"}]'
'HP Mode' = {json(0,{ini_file(Backup,hpMode)})}
json_file './../../json/frequency_lookup.json'
'665 MHz' = {json_file(0,{ini_file(Backup,ramMHzE665)})}
'800 MHz' = {json_file(0,{ini_file(Backup,ramMHzE800)})}
'1065 MHz' = {json_file(0,{ini_file(Backup,ramMHzE1065)})}
json_file './../../json/frequency_lookup.json'
'Latency' = {json_file(0,{ini_file(Backup,ramReadLat)})}{json_file(0,{ini_file(Backup,ramWriteLat)})}


[CPU]
[CPU Table]
;mode=table
;spacing=4
;gap=0
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
mariko:
json_file './../../mariko/cpu_table_lookup.json'
'CPU Table' = {json_file(0,{ini_file(Backup,cpuTableM)})}
json_file './../../mariko/cpu_uv_lookup.json'
'Low UV' = {json_file(0,{ini_file(Backup,cpuUvM)})}
json_file './../../mariko/cpu_uv_high_lookup.json'
'High UV' = {json_file(0,{ini_file(Backup,cpuUvHighM)})}
json_file './../../json/frequency_lookup.json'
'Max Clock' = {json_file(0,{ini_file(Backup,cpuMaxClockM)})}
'Boost Clock' = {json_file(0,{ini_file(Backup,cpuBoostM)})}
json_file './../../json/cpu_vmin_lookup.json'
'Low Vmin' = {json_file(0,{ini_file(Backup,cpuVminLowM)})}
'High Vmin' = {json_file(0,{ini_file(Backup,cpuVminHighM)})}
json_file './../../json/cpu_max_volt_lookup.json'
'Volt Limit' = {json_file(0,{ini_file(Backup,cpuVoltLimitM)})}
erista:
json_file './../../erista/cpu_uv_lookup.json'
'UV' = {json_file(0,{ini_file(Backup,cpuUvE)})}
json_file './../../json/cpu_vmin_lookup.json'
'Vmin' = {json_file(0,{ini_file(Backup,cpuVminE)})}
json_file './../../json/cpu_max_volt_lookup.json'
'Volt Limit' = {json_file(0,{ini_file(Backup,cpuVoltLimitE)})}
json_file './../../json/frequency_lookup.json'
'Boost Clock' = {json_file(0,{ini_file(Backup,cpuBoostE)})}
json '[{"00000000":"Off", "01000000":"On"}]'
'CPU Unlock' = {json(0,{ini_file(Backup,cpuUnlockE)})}

[GPU]
[GPU Table]
;mode=table
;spacing=4
;gap=12
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'

mariko:
json_file './../../json/gpu_uv_table_lookup.json'
'UV Mode' = {json_file(0,{ini_file(Backup,gpuUvM)})}
json_file './../../json/gpu_volt_lookup.json'
'Vmin' = {json_file(0,{ini_file(Backup,gpuVminM)})}
'Vmax' = {json_file(0,{ini_file(Backup,gpuVmaxM)})}
json_file './../../json/gpu_offset_lookup.json'
'Voltage Offset' = {json_file(0,{ini_file(Backup,gpuOffset)})}

erista:
json_file './../../json/gpu_uv_table_lookup.json'
'UV Mode' = {json_file(0,{ini_file(Backup,gpuUvE)})}
json_file './../../json/gpu_volt_lookup.json'
'Vmin' = {json_file(0,{ini_file(Backup,gpuVminE)})}
json_file './../../json/gpu_offset_lookup.json'
'Voltage Offset' = {json_file(0,{ini_file(Backup,gpuOffset)})}


[@More Info]
[UV3 Custom Table]
[UV3]
;mode=table
;spacing=4
;gap=4
ini_file '/atmosphere/kips/.bakHOC/tmp.ini'
mariko:
json_file './../../json/gpu_custom_mariko_lookup.json'
'76 MHz' = {json_file(0,{ini_file(Backup,m76Uv3)})}
'153 MHz' = {json_file(0,{ini_file(Backup,m153Uv3)})}
'230 MHz' = {json_file(0,{ini_file(Backup,m230Uv3)})}
'307 MHz' = {json_file(0,{ini_file(Backup,m307Uv3)})}
'384 MHz' = {json_file(0,{ini_file(Backup,m384Uv3)})}
'460 MHz' = {json_file(0,{ini_file(Backup,m460Uv3)})}
'537 MHz' = {json_file(0,{ini_file(Backup,m537Uv3)})}
'614 MHz' = {json_file(0,{ini_file(Backup,m614Uv3)})}
'691 MHz' = {json_file(0,{ini_file(Backup,m691Uv3)})}
'768 MHz' = {json_file(0,{ini_file(Backup,m768Uv3)})}
'844 MHz' = {json_file(0,{ini_file(Backup,m844Uv3)})}
'921 MHz' = {json_file(0,{ini_file(Backup,m921Uv3)})}
'998 MHz' = {json_file(0,{ini_file(Backup,m998Uv3)})}
'1075 MHz' = {json_file(0,{ini_file(Backup,m1075Uv3)})}
'1152 MHz' = {json_file(0,{ini_file(Backup,m1152Uv3)})}
'1228 MHz' = {json_file(0,{ini_file(Backup,m1228Uv3)})}
json_file './../../json/gpu_custom_mariko_no_auto_lookup.json'
'1267 MHz' = {json_file(0,{ini_file(Backup,m1267Uv3)})}
'1305 MHz' = {json_file(0,{ini_file(Backup,m1305Uv3)})}
'1344 MHz' = {json_file(0,{ini_file(Backup,m1344Uv3)})}
'1382 MHz' = {json_file(0,{ini_file(Backup,m1382Uv3)})}
'1420 MHz' = {json_file(0,{ini_file(Backup,m1420Uv3)})}
'1459 MHz' = {json_file(0,{ini_file(Backup,m1459Uv3)})}
'1497 MHz' = {json_file(0,{ini_file(Backup,m1497Uv3)})}
'1536 MHz' = {json_file(0,{ini_file(Backup,m1536Uv3)})}
erista:
json_file './../../json/gpu_custom_erista_lookup.json'
'76 MHz' = {json_file(0,{ini_file(Backup,e76Uv3)})}
'115 MHz' = {json_file(0,{ini_file(Backup,e115Uv3)})}
'153 MHz' = {json_file(0,{ini_file(Backup,e153Uv3)})}
'192 MHz' = {json_file(0,{ini_file(Backup,e192Uv3)})}
'230 MHz' = {json_file(0,{ini_file(Backup,e230Uv3)})}
'269 MHz' = {json_file(0,{ini_file(Backup,e269Uv3)})}
'307 MHz' = {json_file(0,{ini_file(Backup,e307Uv3)})}
'346 MHz' = {json_file(0,{ini_file(Backup,e346Uv3)})}
'384 MHz' = {json_file(0,{ini_file(Backup,e384Uv3)})}
'422 MHz' = {json_file(0,{ini_file(Backup,e422Uv3)})}
'460 MHz' = {json_file(0,{ini_file(Backup,e460Uv3)})}
'499 MHz' = {json_file(0,{ini_file(Backup,e499Uv3)})}
'537 MHz' = {json_file(0,{ini_file(Backup,e537Uv3)})}
'576 MHz' = {json_file(0,{ini_file(Backup,e576Uv3)})}
'614 MHz' = {json_file(0,{ini_file(Backup,e614Uv3)})}
'652 MHz' = {json_file(0,{ini_file(Backup,e652Uv3)})}
'691 MHz' = {json_file(0,{ini_file(Backup,e691Uv3)})}
'729 MHz' = {json_file(0,{ini_file(Backup,e729Uv3)})}
'768 MHz' = {json_file(0,{ini_file(Backup,e768Uv3)})}
'806 MHz' = {json_file(0,{ini_file(Backup,e806Uv3)})}
'844 MHz' = {json_file(0,{ini_file(Backup,e844Uv3)})}
'883 MHz' = {json_file(0,{ini_file(Backup,e883Uv3)})}
'921 MHz' = {json_file(0,{ini_file(Backup,e921Uv3)})}
'960 MHz' = {json_file(0,{ini_file(Backup,e960Uv3)})}
'998 MHz' = {json_file(0,{ini_file(Backup,e998Uv3)})}
json_file './../../json/gpu_custom_erista_no_auto_lookup.json'
'1036 MHz' = {json_file(0,{ini_file(Backup,e1036Uv3)})}
'1075 MHz' = {json_file(0,{ini_file(Backup,e1075Uv3)})}
