;show_widget=true

[@AMS Settings Page]
[AMS Settings]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'AMS Settings'='HOS {hos_version}AMS {ams_version}'

[*Fan Curve]
;mode=forwarder
package_source './fan_curve.ini'

[GPU Scheduling]
;mode=toggle?on
on:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x1
off:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x0

[Always Save Cheats]
;mode=toggle
on:
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_always_save_cheat_toggles u8!0x1
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_cheats_enabled_by_default u8!0x0

off:
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_always_save_cheat_toggles u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_cheats_enabled_by_default u8!0x0
del /atmosphere/contents/*/cheats/toggles.txt 


[Controller Sync]
;mode=toggle
on:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x1
off:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x0

[Hold R for HB Menu]
;mode=toggle
on:
set-ini-val /atmosphere/config/override_config.ini hbl_config override_key R
off:
set-ini-val /atmosphere/config/override_config.ini hbl_config override_key !R

[gap]
;mode=table
;background=false
;system=mariko
;gap=30

[Notice]
;system=mariko
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=section
'Notice' = ''

[GPU Scheduling Notice Table2]
;system=mariko
;mode=table
;background=true
;wrapping_mode=word
;spacing=4
;gap=25
;section_text_color=warning
'The combination of Scheduling OFF and 1305 MHz exceeds the pmic limit.' = ''