;show_widget=true

[@Manage]
[Manage Modules]

[hoc-clk Persistence]
;mode=toggle?on
;progress=true
on:
exec cPatchHOCCLK ./../../global_cmds.ini
touch ./../../flags/UPDATE_HOC_CONFIG.flag
off:
delete ./../../flags/UPDATE_HOC_CONFIG.flag


[sys-clk-hoc  hoc-clk]
;mode=toggle?off
on:
try:
path_exists './../../data/horizon-oc/atmosphere/contents/00FF0000636C6BFF/'
cp './../../data/horizon-oc/atmosphere/contents/00FF0000636C6BFF/' /atmosphere/contents/00FF0000636C6BFF/
delete /switch/.overlays/sys-clk-overlay.ovl
cp './../../data/horizon-oc/switch/.overlays/horizon-oc-overlay.ovl' /switch/.overlays/
delete /config/horizon-oc/lang/
mkdir /config/horizon-oc/lang/
cp './../../data/horizon-oc/config/horizon-oc/lang/*.json' /config/horizon-oc/lang/
ini_file /config/ultrahand/overlays.ini
set-ini-val /config/ultrahand/overlays.ini 'horizon-oc-overlay.ovl' key_combo "{ini_file(sys-clk-overlay.ovl,key_combo)}"
set-ini-val /config/ultrahand/overlays.ini 'sys-clk-overlay.ovl' key_combo ''
touch './../../flags/USING_HOC_CLK.flag'

off:

try:
path_exists './../../data/sys-clk-hoc/atmosphere/contents/00FF0000636C6BFF/'
cp './../../data/sys-clk-hoc/atmosphere/contents/00FF0000636C6BFF/' /atmosphere/contents/00FF0000636C6BFF/
delete /switch/.overlays/horizon-oc-overlay.ovl
cp './../../data/sys-clk-hoc/switch/.overlays/sys-clk-overlay.ovl' /switch/.overlays/
ini_file /config/ultrahand/overlays.ini
set-ini-val /config/ultrahand/overlays.ini 'sys-clk-overlay.ovl' key_combo "{ini_file(horizon-oc-overlay.ovl,key_combo)}"
set-ini-val /config/ultrahand/overlays.ini 'horizon-oc-overlay.ovl' key_combo ''
delete './../../flags/USING_HOC_CLK.flag'

[*Open Sysmodules]
;mode=forwarder
try:
path_exists /switch/.overlays/ovlSysmodules.ovl
open /switch/.overlays/ovlSysmodules.ovl



[Notice]
[Notice Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=20
;wrapping_mode=word
;section_text_color=warning
'Users must first disable sys-clk-hoc / hoc-clk in Sysmodules before clicking the "sys-clk-hoc  hoc-clk" toggle.'



[@View INI]

[sdmc:/config/horizon-oc/config.ini]

[HOC Config INI Table]
;mode=table
;wrapping_mode=char
;wrapping_indent=true
;spacing=4
list_file_source '/config/horizon-oc/config.ini'