;show_widget=true

[@Manage]
[Manage Modules]

[hoc-clk Persistence]
;mode=toggle?on
;progress=true
on:
exec cPatchHOCCLK ./../../global_cmds.ini
touch ./../../flags/UPDATE_HOC_CONFIG.flag
off:
delete ./../../flags/UPDATE_HOC_CONFIG.flag


[sys-clk-hoc  hoc-clk]
;mode=toggle?off
on:
cp ./../../data/hoc-clk/ /
touch ./../../flags/USING_HOC_CLK.flag
off:
cp ./../../data/sys-clk-hoc/ /
delete ./../../flags/USING_HOC_CLK.flag

[*Open Sysmodules]
;mode=forwarder
try:
path_exists /switch/.overlays/ovlSysmodules.ovl
open /switch/.overlays/ovlSysmodules.ovl



[Notice]
[Notice Table]
;mode=table
;alignment=left
;offset=120
;spacing=3
;end_gap=20
;wrapping_mode=word
;section_text_color=warning
'Users must first disable sys-clk-hoc / hoc-clk in Sysmodules before clicking the "sys-clk-hoc  hoc-clk" toggle.'



[@View INI]

[/config/horizon-oc/config.ini]

[HOC Config INI Table]
;mode=table
;wrapping_mode=char
;wrapping_indent=true
;spacing=4
list_file_source '/config/horizon-oc/config.ini'